//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBibliotecaSisInf.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> PrestamoId { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
