//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBibliotecaSisInf.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public Prestamo()
        {
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public string Garantia { get; set; }
        public string UsuarioCuenta { get; set; }
        public Nullable<int> LibroId { get; set; }
        public Nullable<int> EstudianteId { get; set; }
    
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
